### PR TITLE
Removed unnecessary calls to powertips

### PR DESCRIPTION
**Pull request by SpinStabilized**
PowerTips doesn't appear to be used any longer in the codebase. Running fine without the js files being referenced in the HTML files.

### CODE REVIEW

**Comment by catsgotmytongue** [comment]
This PR would remove tooltips from things like cost:
image

**Review by catsgotmytongue — COMMENTED** [review]
I'm not comfortable putting this in as  it would remove tooltips on things like cost:
image

**Comment by catsgotmytongue** [comment]
To be clear I'm not opposed to  removing jQuery where possible but powertips is definitely in use and there are several calls to jQuery that could be replaced with something more modern.

**Comment by SpinStabilized** [comment]
I'm ok with that. I'm just trying to lower the code base, didn't notice the tooltips. I thought it was UI layout tips like hints in QT.

Looking for ways to bring it up to more current versions without breaking everything. I will try a version that uses a CDN to get the library so that we don't have to worry about maintaining a library within our codebase, just a version pointer to the library hosted elsewhere.

**Comment by catsgotmytongue** [comment]
@SpinStabilized FYI, After spending some time reading the code of this application, I opted to build something new instead of try to make this one modern. I'm building it in angular with typescript and plan on sharing it and giving it an open source license when I have it to a working stable point.

PRs are welcome for anything that is fixing an issue - though it isn't my repo I helped get a build going and have made some contributions and do some reviews.

**Comment by SpinStabilized** [comment]
Thanks! I had been thinking about writing a version for Django and keeping the database as a SQLite file too. I just don't have the bandwidth to dedicate to a full development effort right now as my day job has gotten really busy as we approach a huge milestone. I think anything that brings the whole thing to a modern web standard would be amazing.

**Pull request closed without merging**
