### PR TITLE
Fixed Vanik rules and tested locally.

### PR DESCRIPTION
**Pull request by MrKeon**
Added a utility function to check if current visiting (I believe this app uses the visitor design pattern?) upgrade card is occupying a tech slot on the ship. Added this to the Vanik rules and used this instead of checking the type of the upgrade.

### CODE REVIEW

**Review by catsgotmytongue — COMMENTED** [review]
When I tested locally with the following set of cards Vanik didn't provide a discount to Advanced Shields.

http://localhost:8000/#eyJzaGlwcyI6W3siaWQiOiJzaGlwOlMwOTEiLCJjYXB0YWluIjp7ImlkIjoiY2FwdGFpbjpDYXA1MjIiLCJ1cGdyYWRlU2xvdHMiOlt7fV19LCJ1cGdyYWRlcyI6W3siaWQiOiJ0ZWNoOlQwMTQifSx7fSx7fSx7fSx7ImlkIjoiY3JldzpDMTU0IiwidXBncmFkZVNsb3RzIjpbe30seyJpZCI6InRlY2g6VDA4NSJ9XX1dfV19

I'm not sure what problem getOccupiedSlot was trying to solve but upgrade.type == 'tech' should have made discounts apply correctly as far as I can tell, am I missing a case where this didn't already work ?

**Review by catsgotmytongue — CHANGES_REQUESTED** [review]
I haven't looked at the code base in a while. 
The question card itself would be the 'upgrade.type' which is not 'tech' but 'question' in some cases. 

in my local development environment I added some things, I have not had time to really thoroughly test it but it seems to work.

a 'hasAnyFaction' function below the hasFaction function to be a bit more elegant in some conditions, instead of string a bunch of '||' s together that are doing the same thing as this:
```
	hasAnyFaction: function(card, factions, ship, fleet) {
		return factions.some(f => this.hasFaction(card, f, ship, fleet));
	},
```
I believe the problem is that upgrade.type being 'tech' is not enough and getOccupiedSlot by itself was not enough, try these changes (note I changed getOccupiedSlot to return the object used to represent the slot instead of the type's first element):
```
	var getOccupiedSlot = function(upgrade, ship){
		var id = upgrade.id;
		for ( var i = 0; i < ship.upgrades.length; i++) {
			var slotUpgrade = ship.upgrades[i];
			if (slotUpgrade?.occupant?.id == id) {
				return slotUpgrade;
			}
		}
		return null;
	}
```

```	
// in the vanik section, I added the following:
		// Vanik
		"captain:Cap522": {
			intercept: {
				ship: {
					// All Vulcan/Federation tech is -2 SP
					cost: function(upgrade, ship, fleet, cost) {
					if( $factions.hasAnyFaction(upgrade,["federation","bajoran", "vulcan"], ship, fleet) && (upgrade.type == "tech" || getOccupiedSlot(upgrade, ship)?.type?.includes("tech") ))
							return resolve(upgrade, ship, fleet, cost) - 2;
						return cost;
					},
				}
			}
		},
```

**Comment by MrKeon** [comment]
@catsgotmytongue , I updated the PR with your recommendations and successfully tested locally :)

**Comment by catsgotmytongue** [comment]
Looks good, I'll merge

**Review by catsgotmytongue — APPROVED** [review]

**Pull request merged**
