### PR TITLE
Add redirect for URL change

### PR DESCRIPTION
**Pull request by Relequestual**
Fixes Primary URL change #46

I haven't tested this locally. I attempted the fix via GitHub codespaces.
Frustratingly, I couldn't work out how to push my changes to my fork. Probably should have opened the codespace ON the fork.

I didn't have time to look into that specifically further.
Please validate the change works as expected before merging. Provided untested.

### CODE REVIEW

**Comment by Relequestual** [comment]
Looks like codespaces made a bunch of whitespace changes, removing indentation on blank lines.

**Comment by catsgotmytongue** [comment]
I would test locally before pushing to main.

I see the src/index.html getting updated. This doesn't make sense to me as if it is at this index.html then it is already at a url without the '/staw-utopia/' segment in the url already isn't it ?

**Comment by catsgotmytongue** [comment]
codespaces is a VM that can be run with a devcontainer. The indentation and whitespaces changes were made by something else.

We should use linting like ESlint or something to standardize whitespace and 'prettier' to keep things consistent for the project - eslint is part of one of the build steps already but it may need some work.

**Comment by catsgotmytongue** [comment]
Wait I see what you are doing now.

this will add a staw-utopia sub folder with a index.html that redirects to the main index.html.
I would say this line, needs to add index.html as replacement just to be on the safe side:
window.location.href = window.location.replace('staw-utopia/index.html', '')

probably needs to be this:
window.location.href = window.location.replace('staw-utopia/index.html', 'index.html')

nothing has been tested locally yet.

**Review by catsgotmytongue — APPROVED** [review]

**Pull request merged**
