### PR TITLE
Fix prime faction with refactor to  check for prime factions when checking factions

### PR DESCRIPTION
**Pull request by catsgotmytongue**
I put this in the code comments as well, longer comments than I usually write but very explanatory:

  
experimental fix, remove factionPenalty function and instead check for 'prime factions' in $factions.hasFaction - this eliminates code like the following:
 $factions.hasFaction( ship, "vulcan", ship, fleet ) ? 0 : 1 && $factions.hasFaction( ship, "bajoran", ship, fleet ) ? 0 : 1

as a prime faction can easily be checked without checking each and every sub faction.

note: all cards that already have an overridden factionPenalty function as a cardRules entry will continue to work as they did before.

So I now lose nothing (theoretically) by commenting out George Sanders - feel free to test this on my repo's version of the page: https://catsgotmytongue.github.io/Star-Trek-Attack-Wing-Utopia

We no longer should need code like the following, which I saw hundreds of times I think.

//George Sanders
// "captain:Cap016":{
// 	factionPenalty: function(upgrade, ship, fleet) {
// 		return ship && $factions.hasFaction( ship, "vulcan", ship, fleet ) ? 0 : 1 && $factions.hasFaction( ship, "bajoran", ship, fleet ) ? 0 : 1;
// 	}
// },

This should also work with the independent prime faction and its sub factions, eliminating a lot of redundancy :)

I would carefully remove these kinds of factionPenalty() overrides taking note that some may still be necessary if they do have a special faction penalty like +3SP if not on a federation ship or whatever the card says.

### CODE REVIEW

**Comment by AngryTribble** [comment]
Sounds good to me

**Review by AngryTribble — APPROVED** [review]
This looks great!

**Review by AngryTribble — APPROVED** [review]
Reviewed

**Comment by catsgotmytongue** [comment]
Ok, these changes appear to have been committed to the main branch independent of my PR as they were copied into the main branch manually.

**Pull request closed without merging**
